modules/portunus.nix
=> Portunus assert

flake.nix, lib/doc.nix
=> Add mkOptionsJSON

.github/workflows/gh-pages.yaml
=> Update build names

modules/initrd.nix, modules/nvidia.nix
=> Nvidia cleanup

modules/hound.nix
=> hound: add repos convenience option

modules/home-assistant.nix
=> home-assistant: don't log missing function

flake.nix, modules/prometheus.nix
=> prometheus: add blackbox-exporter helper

flake.nix, lib/debug-pkgs.nix, modules/debugging.nix
=> Add debugging shell/module

flake.lock, flake.nix
=> Use nuschtpkgs

.github/workflows/template-sync.yaml
=> Fix sync template

.github/workflows/template-sync.yaml
=> Fix template sync

.editorconfig, .github/workflows/update-flakes.yaml
Merge https://github.com/NuschtOS/template f94d1fb
=> upstream merge template repository

modules/matrix.nix, modules/postgres.nix
=> Replace deprecated mkPackageOptionMD

modules/grafana.nix
=> grafana: drop configureRedis

modules/nix.nix
=> nix: add git to make flakes useful

modules/intel.nix
=> intel: fix vainfo

modules/nvidia.nix
=> nvidia: cleanup

modules/vaultwarden.nix
=> vaultwarden: fix after 1.31.0 update

modules/home-assistant.nix
=> home-assistant: add more imperative files

modules/git.nix, modules/gitea.nix, modules/grafana.nix
=>  gitea: display dex login with domain;  git: add delta, recommended defaults 

modules/mailman.nix
=> mailman: init

modules/mailman.nix
=>  mailman: fix mailman conditions,  fix callbackURL

modules/mailman.nix
=> mailman: fix postgres connection

README.md
=> Update tag line

modules/portunus.nix
=> Portunus followup

modules/gitea.nix, modules/mastodon.nix, modules/portunus.nix
=> Mastodon OIDC

modules/intel.nix, modules/nextcloud.nix
=> Nextcloud nixos-unstable

modules/dex-session-cookie-password-connector-2.41.patch, modules/portunus.nix
=> portunus: add patch for dex 2.41.x

modules/slim.nix
=> slim: add speechd related services

modules/slim.nix
=> slim: fix stable compatibility

modules/nix.nix
=> nix: don't duplicate git/gitMinimal

modules/no-graphics-packages.nix, modules/no-x-libs.nix
=> Add environment.noGraphicsPackages, a environment.noXlibs replacement

.github/workflows/flake-eval.yaml, flake.nix
=> Ci updates

modules/slim.nix
=> slim: disable speech synthesis in thunderbird

modules/kresd.nix
=> kresd: add kresd-cli

modules/slim.nix
=> slim: fix merging

modules/nginx.nix
=> nginx: add hstsHeader.includeSubDomains option

modules/postgres.nix
=> postgres: refreshCollation for all dbs

flake.nix, modules/postgres.nix
=> postgres: add vacuumAnalyzeTimer option

modules/hedgedoc.nix, modules/home-assistant.nix, modules/ldap.nix, modules/matrix.nix
=> ldap: add an user serverURI option

modules/intel.nix, modules/nvidia.nix
=> intel/nvidia: enable hardware.graphics automatically

modules/no-graphics-packages.nix
=> no-graphics-packages: fix mesa

README.md, modules/acme.nix, modules/containers.nix, modules/debugging.nix, modules/default.nix, modules/home-assistant.nix, modules/initrd.nix, modules/mailman.nix, modules/mastodon.nix, modules/matrix.nix, modules/nextcloud.nix, modules/nginx.nix, modules/nix.nix, modules/portunus.nix, modules/simd.nix, modules/slim.nix, modules/ssh.nix, modules/vaultwarden.nix, modules/zfs.nix
=> Improve readme and some cleanup

flake.lock, flake.nix
=>  search-page: set title 

modules/strace.nix
=> strace: add with colors patch option

modules/no-graphics-packages.nix
=> no-graphics-packages: fix eval on stable

modules/nix.nix
=> Fix missing trusted-user

modules/gitea.nix
=> Fix shellcheck findings with enableStrictShellChecks enabled

README.md, modules/matrix.nix
=> Drop sliding sync

.github/renovate.json
=> Drop postUpgadeTasks

.github/renovate.json
=> Group flake inputs

modules/grafana.nix, modules/matrix.nix
=>  matrix: bump providers.json hash; fix some nginx groups

modules/ssh.nix
=> Ssh ssh keygen key mismatch

modules/users.nix
=> users: add option to run systemctl --failed on login

README.md
=> Add matrix chat

flake.lock, flake.nix
=> Drop search

modules/nix.nix
=> nix: add remoteBuilder example

modules/postgres.nix
=> postgres: improve doc

modules/postgres.nix
=> postgres: add some good defaults for stopServices

modules/renovate.nix
=> renovate: fix condition on nixos-unstable

modules/gitea.nix
=>  gitea: allow registration via oidc, reduce logging noise 

.github/workflows/post-compare-link.yaml
=> Add post-compare-link action

modules/nix.nix
=> nix: fix nixos-rebuild with --target-host and --build-host

flake.lock, modules/matrix.nix
Requires https://github.com/NixOS/nixpkgs/pull/355225 but has a fallback.
=> matrix: merge element conf changes

modules/no-graphics-packages.nix
=> no-graphics-packages: fix mpv on unstable

.github/workflows/flake-check.yaml
=> Add 24.11 to CI

modules/portunus.nix, modules/prometheus.nix
=>  prometheus: add blackbox dns prober 

modules/prometheus.nix
=> Blackbox probe fixes

modules/prometheus.nix
=> prometheus: don't duplicate ip6 in names when only doing it

modules/firefox.nix, modules/intel.nix, modules/nextcloud.nix
=> Remove duplicated intel module with nixos-hardware

modules/no-graphics-packages.nix
=> no-graphics-packages: remove kernel rebuild

modules/matrix.nix
=> matrix: bump oembed provider

modules/nix.nix
=> nix: add xdg based directories

modules/nix.nix
=> nix: forward arguments correctly

modules/mastodon.nix
=> mastodon: move birdUI to overlay

flake.lock, tests/default.nix
=>  Fix nextcloud test eval 

modules/home-assistant.nix
We cannot add an alias as that conflicts with the new upstream options...
Closes #188
=> home-assistant: drop blueprints option which has been upstreamed

modules/grafana.nix, modules/vaultwarden.nix
Based on https://github.com/dvershinin/gixy/pull/15#issuecomment-2661823516
=> Match files in location block exactly

modules/grafana.nix
=> fix grafana socket

modules/ssh.nix
See https://redirect.github.com/NixOS/nixpkgs/pull/378875
=> ssh: update KexAlgorithms

.github/workflows/flake-check.yaml, modules/no-graphics-packages.nix
=> Drop nixos-24.05 support

modules/postgres.nix
=> postgres: better extension loading

modules/vim.nix
=> vim: cleanup

modules/hound.nix
=> hound: cleanup 24.11

modules/postgres.nix
I picked https://github.com/NuschtOS/nuschtpkgs/commit/bb181e86270cad17a69982554af94dc47353ed17 into backports-24.11. Not sure how to properly fix that.
=> postgres: fix finalPackage not being there on 24.11

modules/zfs.nix
=> zfs: remove latestCompatibleKernel

modules/grafana.nix, modules/home-assistant.nix, modules/hydra.nix, modules/matrix.nix
=> Add more configurePostgres options

modules/slim.nix
=> slim: cleanup pre 24.11 conditionals

modules/mastodon-bird-ui.patch, modules/mastodon.nix
=> mastodon: switch to more up to date bird-ui

modules/home-assistant.nix
=> home-assistant: fix typo

modules/nextcloud.nix
=> nextcloud: drop configureRecognize in favor of upstream package

modules/nextcloud.nix
Not useful without https://github.com/NixOS/nixpkgs/pull/388067
=> nextcloud: use memories app if available

modules/nextcloud.nix
=> nextcloud: fix memories app condition

modules/portunus.nix
=> portunus: fix oauth2-proxy service config, enable pkce

modules/postgres.nix
=> postgres: fix shared_preload_libraries containing empty strings

modules/postgres.nix
=> postgres: fix postgis loading

modules/postgres.nix
=> postgres: add gancio

modules/matrix.nix
=> matrix: add synapse-admin option

modules/simd.nix
=> simd: enable experimental-features just in case

modules/matrix.nix
=> matrix: use synapse-admin-etkecc if available

modules/postgres.nix
=>  postgres: add pgRepackTimer option 

modules/matrix.nix
=> matrix: decrease synapse logging

modules/tmux.nix
=> Improve tmux

modules/nginx.nix
=> nginx: don't use aws-lc with kTLS

.github/workflows/flake-check.yaml, modules/nextcloud.nix, modules/nvidia.nix, modules/postgres.nix, tests/default.nix
=> Update to NixOS 25.05

.github/workflows/flake-check.yaml
=> Switch to nix-community nix cache action

.github/workflows/flake-check.yaml
=> Fix ca-derivation enabling

modules/haproxy.nix
=> haproxy: add recommendedDefaults

.github/workflows/flake-check.yaml
=> Fix ca-derivations

.github/workflows/flake-check.yaml
=> Set extra-experimental-features explicitly

flake.lock, modules/nginx.nix
=>  nginx: disable pcre2's jit sealloc 

modules/postgres.nix
=> postgres: simplify condition

modules/mastodon.nix, modules/nginx.nix, modules/postgres.nix
=>  mastodon: update bird-ui patch, nginx: fix aws-lc for 1.28.0

modules/initrd.nix
=> initrd: add missing toString

modules/nginx.nix
=> nginx: remove recommendedZstdSettings

flake.lock, modules/renovate.nix
=> renovate: clean up hackery

modules/nginx.nix, tests/default.nix
=> Nginx aws-lc fixes

modules/strace.nix, tests/default.nix
=> strace: use merged patch

modules/grafana.nix, modules/harmonia.nix, modules/minio.nix, modules/vaultwarden.nix
=> minio: add

.github/workflows/flake-check.yaml, modules/chrony.nix
=>  chrony: add 

modules/postgres.nix
=> postgres: fix condition

modules/postgres.nix
=> postgres: add mediagoblin services

modules/ssh.nix
=> ssh: add codeberg keys

modules/initrd.nix
=> initrd: add check if all interface drivers are loaded
