modules/nextcloud.nix
Resolves the issue of nodejs_16 being EOL upstream in nixpkgs
It seems while https://github.com/nextcloud/recognize/issues/985 is open and possibly being worked on upstream in recognize, a user can work around this via the built-in option to define node location (the use of path will obviously be fragile here to nixpkgs updates, but for now it's working in my testing)
Current settings as per: `/settings/admin/recognize`
Happy to wait for upstream to resolve this with said, if that is the preference :+1:
=> nextcloud: update node to v20

modules/portunus.nix
=> portunus: fix user ldap filter containing objectClass twice

modules/portunus.nix
=>  portunus: make oauth2-proxy useful when portunus is not running locally 

modules/no-x-libs.nix
The option was only introduced in https://github.com/NixOS/nixpkgs/pull/313844
I wonder how that ever worked. Maybe I cherry-picked things from that PR and they already rebased out of my fork and in the review they changed the default from true to false.
=> Drop no longer required override

modules/gitea.nix
The gitea command in the authorized_keys file might have changed
=> gitea: sync ssh keys on startup.

modules/postgres.nix
@MarcelCoding can you test this on your config?
I've tested the refresh collation on a server and it worked as expected:
```
postgresql-post-start[123456]: NOTICE:  changing version from 2.38 to 2.39
```
=> postgres: create refreshCollation option, add user password option

modules/postgres.nix
=> postgres: error when postgres version is to old for collation

modules/postgres.nix
=> postgres: add a warning when not using the latest postgres

modules/portunus.nix
=> portunus: add groups scope to oauth2-proxy if the nginx proxy config requires it

modules/harmonia.nix
=> harmonia: disable nginx by default

modules/grafana.nix
=> grafana: fix admin password assertion

modules/ldap.nix
=> ldap: drop useless types.submodule

modules/containers.nix
Error: system prune --external cannot be combined with other options
Also I haven't used anything "external" myself, so don't bother with it for now.
=> containers: drop --external flag

modules/nextcloud.nix
I missed the chance to test the After= with the nextcloud update but it now matches nextcloud-cron.
=> nextcloud: fix Imaginary

modules/postgres.nix
=> postgres: use major version 17 if available

modules/prometheus.nix
=> prometheus: don't cause error on empty config

modules/postgres.nix
=> postgres: add more annoying prompt for postgres updates

modules/containers.nix
=> containers: sync podman with docker

modules/nginx.nix
=> nginx: disable tcpFastOpen in opinionated settings

modules/home-assistant.nix
=> home-assistant: add zigpy OTA url

modules/nginx.nix
=> nginx: allow disabling individual recommended settings without mkForce

modules/home-assistant.nix, modules/postgres.nix
=>  home-assistant: expand recommended default settings, fix eval when home-assistant db_url is not set

modules/postgres.nix
Note: I'm not running with `cfg.enableAllPreloadedLibraries` or `cfg.configurePgStatStatements`enabled, so testing this mostly just included checking the settings existed and that my dotfiles built.
Addresses the following build failure:
```shell
… while evaluating the option `system.build.toplevel':
… while evaluating definitions from `/nix/store/6win34qzpvg1vahlc4iq0nhy1hbh90jg-source/nixos/modules/system/activation/top-level.nix':
… while evaluating the option `warnings':
… while evaluating definitions from `/nix/store/6win34qzpvg1vahlc4iq0nhy1hbh90jg-source/nixos/modules/system/boot/systemd.nix':
… while evaluating the option `systemd.services.postgresql.serviceConfig':
… while evaluating definitions from `/nix/store/6win34qzpvg1vahlc4iq0nhy1hbh90jg-source/nixos/modules/system/boot/sys …
```
=> postgres: fix double cfg on pg_stat_statements install

modules/nginx.nix
Don't silently drop common config if hsts is not enabled
=> nginx: fix common server config

modules/nix.nix
like with the other two code paths
=> nix: use hard coded arguments for nix-store

modules/nix.nix
=> nix: don't require mkForce to change connect-timeout

modules/containers.nix
=> containers: fix networking when nftables is activated

modules/matrix.nix
=> matrix: use priority instead of regex hacks

modules/nix.nix
https://github.com/NixOS/nix/pull/12876
=> nix: decrease connect timeout to 2.29 default

modules/nginx.nix
=> nginx: always use newer nginx version between stable and mainline

modules/prometheus.nix
=> Various blackbox exporter improvements

modules/postgres.nix
=> postgres: add empty backupAll option to fix search build

modules/chrony.nix
=> chrony: use mkDefault to avoid mkForce downstream

modules/portunus.nix
=> portunus: ignore /oauth2/auth in oauth2-proxy
